# Generated by Django 2.2.4 on 2019-08-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0002_auto_20190826_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planets',
            options={'ordering': ['name'], 'verbose_name': 'Планета', 'verbose_name_plural': 'Планеты'},
        ),
        migrations.AlterModelOptions(
            name='recruits',
            options={'ordering': ['name'], 'verbose_name': 'Рекрут', 'verbose_name_plural': 'Рекруты'},
        ),
        migrations.AlterModelOptions(
            name='sith',
            options={'ordering': ['name'], 'verbose_name': 'Ситх', 'verbose_name_plural': 'Ситхи'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ['order_code'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='planets',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Планета'),
        ),
        migrations.AlterField(
            model_name='recruits',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='recruits',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Емаил'),
        ),
        migrations.AlterField(
            model_name='recruits',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя рекрута'),
        ),
        migrations.AlterField(
            model_name='recruits',
            name='planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='si.Planets', verbose_name='Планета'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя ситха'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='planet',
            field=models.ForeignKey(on_delete=models.SET('0'), to='si.Planets', verbose_name='Планета'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='list_questions',
            field=models.CharField(max_length=200, verbose_name='Список вопросов'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='order_code',
            field=models.IntegerField(unique=True, verbose_name='Код ордена'),
        ),
    ]
